### ISSUE TITLE
Problems in data preparation steps

### ISSUE THREAD

**Issue by leeinscky** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#12]
"Thanks for pointing that out! As you can see from the comment, that section is to generate multiple batches of data in case the raw data file is too large. But before that, "single" function will basically do similar thing and just put all data in one file. You can comment out that section and gave it a try. 

Just let me know if you have more questions! :) "

_Originally posted by @rayguan97 in https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/issues/4#issuecomment-579454136_

Hi, thank you for the share of codbase, I am also new to the trajectory prediction area and try to run the data preparation steps. But there are two problems confusing to me.

Question 1:
I tried to comment out that section as you suggested in https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/issues/4

I ran the data_processing/generate_data.py with the following three commands:

python generate_data.py --set train
python generate_data.py --set val
python generate_data.py --set test

After that, I found that three files: trainSet.txt, valSet.txt, testSet.txt will be automatically created in resources/data/ARGO, but I noticed that there was no data in these three files, which means the code only created these three files but wrote nothing in them. I guess it was caused because I commented out that section. So I guess the line 165 to 185 is necessary. But in line 168 of data_processing/generate_data.py, the code seems to be not finished, could you help me to complete or improve the line 165 to 185 of data_processing/generate_data.py ?

Besides, in line 165-166 of data_processing/generate_data.py, could you explain the function of these two statements? 

Question 2:
In line 24-30 of data_processing/data_stream.py, the DATA_DIR for APOL and LYFT both includes trainSet0.txt, but I only found the statements that can create trainSet.txt for ARGO in data_processing/generate_data.py. 

I did not find any statements that can help to create trainSet.txt file in these two files: 
1.data_processing/format_apolloscape.py
2. data_processing/format_lyft.py. 

After I ran the above two files, I did not find  trainSet.txt in resources/data/APOL/train and resources/data/LYFT/train, which were expected to be there.

I would be grateful if you could help me with it.

Thank you very much for your attention and help.

**Comment by rayguan97** [comment]
Hi, let me answer your questions and hopefully it will help.

1. The two files are updated, generate data.py and format_argo.py.
In generate_data.py, it should be working now. As to line 165-166, this is for Apolloscape and lyft dataset to prepare input for sgan, traphic and social conv methods. 
From 171 to 187, it will scan all files in argo dataset(in train, val or test) and create a file to each set. Since there are too many of them, then we run merge to put some of the data together.

2. @srujanpanuganti I'll leave it to him to address the issue with format_apolloscape.py and format_lyft.py. 

Hope this will help!

**Comment by srujanpanuganti** [comment]
Hi @leeinscky Thanks for pointing this out. Looks like we have created the files manually here. We will update the code to automatically create those files. 

Regards,
Srujan

**Comment by leeinscky** [comment]
Hi, thank you for your answer. The updated code for the first question worked well now. But I got another problem as below.

Question 3:
Does "FIRST" in line 138 of TraPhic/data_processing/data_stream.py be a global variable? It seems that the value of  "FIRST" is not defined. I got the following error:

Traceback (most recent call last):
  File "data_stream.py", line 368, in <module>
    data_for_stream2 (DATA_DIR, train_seq_len = train, pred_seq_len = pred, frame_lenth_cap = train + pred)
  File "data_stream.py", line 169, in data_for_stream2
    d_IDs = np.unique (data [:, 4]). astype (int) [: FIRST]
NameError: name 'FIRST' is not defined

**Comment by rayguan97** [comment]
You can define a FIRST variable. This is the number of agents you want to extract.

**Comment by leeinscky** [comment]
Thank you. Could you introduce the specific steps to generate the following .pkl files in TraPhic/resources/data/ARGO ?
![image](https://user-images.githubusercontent.com/54604936/74205548-d20a4700-4cb2-11ea-8e25-3104eaaeb88e.png)

I have successfully run the following steps, what should be the remaining steps?
1. Run data_processing/generate_data.py to format the downloaded Argoverse trajectory data into our desired representation
2. Run the data_for_stream1 and data_for_stream2 function in data_stream.py.

Besides, it seems that the parameters settings of save_to_pkl function in data_stream.py has not been introduced, could you please look into this, thank you.

**Comment by srujanpanuganti** [comment]
@leeinscky The above issue is now resolved.
