### ISSUE TITLE
NaN when training the model

### ISSUE THREAD

**Issue by xinshuoweng** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#13]
Hi,

Thank you for making open-source code. I have one implementation question as titled. When I train the model in "Ours", the stream 1 always gives NaN in the loss. Why does this happen? is there any fix to it?

**Comment by rayguan97** [comment]
Thank you for your feedback! 

After look into it, please check 100-104 line in ours/def_train_eval.py. This will load our trained models directly before training. After removing those lines, you should be able to get some numbers. Directly evaluating those models with correct setup and arguments should get you the best numbers in the paper.

Let me know if you have any other questions

**Comment by xinshuoweng** [comment]
Thank you!
