### ISSUE TITLE
Regarding evaluation of Stream 2

### ISSUE THREAD

**Issue by naveenkumar1311** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#14]
Hi, 
Right now I am interested and working on understanding and regenerating results for Stream 2. But I see in ours/main.py there is only stream 1 evaluation. Can you please answer my following query

Q) how to use pre-trained stream-2 encoder-decoder models to produce eigenvectors, I tried to replicate the procedure done for stream1 in eval function in def_train_eval.py but I am unable to figure out the inputs and outputs to be sent.

**Comment by rohanchandra30** [comment]
As of February 2020, we have not added the evaluation code for stream 2, since it is not ready to be uploaded. But we will get to it very soon and will update this issue.
