### ISSUE TITLE
Computer gets stuck when evaluating traphic_sconv in comparison method

### ISSUE THREAD

**Issue by xinshuoweng** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#15]
Hi,

As titled, when I simply use the provided trained model to evaluate the performance of the traphic_sconv by python3 main.py, the computer gets stuck and has to be restarted. Have you ever noticed this problem?

**Comment by rohanchandra30** [comment]
Hmm, I have not noticed this problem. I am currently at AAAI'20 in New York and will be back on Thursday. I will take a look and let you know if I encounter this issue.

**Comment by rohanchandra30** [comment]
Are you noticing this problem only for traphic_sconv method? Or for other methods as well?

**Comment by xinshuoweng** [comment]
Thanks for your quick reply! Only for traphic_sconv.

**Comment by xinshuoweng** [comment]
Let me try to pinpoint which exact line of code causes this and will let you know.
