### ISSUE TITLE
Testing on Custom Dataset

### ISSUE THREAD

**Issue by sayyidabeegam** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#22]
how can I test with my input?
means by giving the trajectory information how can I produce the predicted data corresponding to that in EncDec?

**Comment by rohanchandra30** [comment]
1. The first step is to prepare your dataset in our format which is that each row will contain <Frame ID>, <Vehicle ID>, <X coordinate>, <Y Coordinate>, <Dataset ID>.

2. Convert to .npy format and save this as "TrainSet0.npy".

3. Run the datastream.py file  in /data_processing. This will generate the pickle files needed to run the main.py files for any method.

4. Then run the main.py file of any method.

These are broad steps and you may have to adjust parameters, path issues and other small bugs. I am currently working to make this more automated and bug-free. But give this a try and let me know if you have issues with these steps first.

**Comment by srujanpanuganti** [comment]
Here's more detail about working with custom data

1. The first step is to prepare your dataset in our format which is a text file where each row will contain 'Frame ID', 'Agent_ID', 'X coordinate', 'Y Coordinate', 'Dataset_ID'.

Mandatory precautions to take while preparing to our format:
a. Make sure your Frame_ID's range between `1 to n`. and Agent_ID's also range from `1 to N`.`n` is total number of frames and `N` is total number of agents. If your dataset uses a different convention to represent the Frame_ID's (for example, few datasets use Time Stamp as frame ID), you need to map these ID's to `1 to n`. If your dataset uses a different convention to represent Agent_ID's (for example few datasets represent Agent_ID's using string of characters), you need to map these ID's to `1 to N`. 
b. If the Frame_ID's and Agent_ID's of your dataset are already in ranges of `1 to n` and `1 to N`, make sure they are sequntial. Make sure there are no missing ID's. 
c. Make sure the text file is formed in such a way that Frame_ID's are in increasing order, starting from 1 to n. To double check, if you have successfully formatted your data into our format, the first few rows will have repeated Frame_ID's and the corresponding Agent_ID's of these repeated Frame_ID's must not be repeating.   
d. Dataset_ID's are used to differentiate different scenes/sets of a same DATASET

2. Convert the text file to `.npy` format and save this as `TrainSet0.npy`.

3. Run the `data_stream.py` file in /data_processing. This will generate the pickle files needed to run the `main.py` files for any method.

Mandatory precautions to take before running `data_stream.py`:
a. Make sure you taken all the mandatory precautions before running `data_stream.py`
b. You must know the frame rate at which the trajectories of the vehicles are recorded. i.e., you must know how many frames does 1 second corresponds to? Few datasets are sampled at a frequency of 2Hz. This means each seconds corresponds to 2 frames in the dataset. 
c. You must give the appropriate `train_seq_len` and `pred_seq_len` based on what rate the data is sampled at. For example, if the data is sampled at 2Hz, then 1 second corresponds to 2 frames. if you want to consider 3 seconds as observation data, then `train_seq_len` would be `3*2 = 6`. if you want the to consider next 5 seconds as prediction data, then `pred_seq_len` would be `5*2 = 10`. Make sure the `frame_lenth_cap >= (train_seq_len + pred_seq_len)`. We use this `frame_lenth_cap` to enforce that an `Agent_ID` is present/visible/seen in atleast `frame_lenth_cap` number of frames. 
d. If your data is too huge, you may want to consider only few scenes/sets from the whole data. Use the D_ids list to tweak the values and shorten the amount of data.
e. Assign a short keyword `XXXX` for naming your dataset
f. Expect to see multiple files generated in the `./resources/DATA/XXXX/ ` with names starting with `stream1_obs_data_, stream1_pred_data_, stream2_obs_data_, stream2_pred_data_,stream2_obs_eigs_, stream2_pred_eigs_`

4. Then run the `main.py` file of any method.

**Comment by rohanchandra30** [comment]
The instructions above have been added to the repo ReadMe
