### ISSUE TITLE
About running the comparison method/traphic_conv

### ISSUE THREAD

**Issue by BenMSK** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#23]
Hello, at first, thank you for sharing this amazing job. I am really into it.
I've tried to run the traphic_conv method, and have followed the instruction.
I have some questions for running the method.

I downloaded APLO dataset, and unzip the files; sample_trajectory.zip and prediction_test.zip (by following comments in formatted_apolloscape.py)
And then, using the formatted_apolloscape.py, I generated the {train/val/test}Set0.npy in resources/data/APOL/{train/val/test}/.
Then, I run the main.py in /comparison_method/traphic_sconv/, but I've got a following error.

'FileNotFoundError: [Errno 2] No such file or directory: '../../resources/data/APOL/train/trainSet0-traj.npy'
So, I've changed the file name to {train/val/test}Set0-traj.npy, but there needs {train/val/test}Set0-track.npy, too.

1. What does. the trainSet0-traj, -track. each means? I've been confused it.

2. I made temporary Set0-traj, track file, but the shape of training data is a bit different from what the main.py needs. 
For example, if I generate the {train/val/test}Set0.npy by the formatted_apolloscape.py, this .npy has 5 columns;{frame_id, object_id, x, y, dataset_id}. 
But in line 80ish '/traphic_sconv/model/Prediction/utils.py', self.D = d[0], which means it only gets the first row, and in line 125ish, 'grid = self.D[idx,8:47] # Nhbr Info' which means there has to be futher columns.
What data construction 'Set0.npy' has, for running the main.py?

3. I've analyzed the code, line by line; I am a bit confused about the meaning of the argument '[dsId]'. Does it mean the dataset id? like APOL for 4, ARGO for 3

4. Could you explain the whole instruction for running 'traphic_conv'? It will be a great help.

I plan to use APOL dataset; 

Thanks,

[little update; 20.04.03]
I found that in 'main.py', there are lines for generating 'Set{}-traj, -track' .

'	train_loc = RAW_DATA + '/train/data/'
	output_dir = RAW_DATA + '/train/formatted/'
	files = [f for f in os.listdir(train_loc) if '.txt' in f]
	train_lst = argo_to_formatted(train_loc, files, output_dir, "train")
	create_data(output_dir, files, train_lst, args.dir, "train")
~'
which are commented lines.

Do I need to use these for generating the file the main.py needs?

**Comment by rohanchandra30** [comment]
Thanks, we'll look into this and get back to you soon !

**Comment by rayguan97** [comment]
1. please refer to Spectral-Trajectory-and-Behavior-Prediction/comparison_method/traphic_sconv/model/import_data.py, line 16 - 71 for how to generate track.npy and traj.npy. The input should be the npy file you get as you mentioned above. This is also called in Spectral-Trajectory-and-Behavior-Prediction/comparison_method/traphic_sconv/main.py line 120. You should call it after you generated npy file.  (The pipeline for argo is in that file, but not for apol. But once you have .npy, track.npy and traj.npy should be easy to get.) 

2 & 3. self.D = d[0] means we are only getting one dataset with id 1 from the whole dataset. dsID means the dataset id. All of those sets are within a same dataset, not like 1 is for ARGO and 2 is for APOL. One you properly generate all traj and and track, the shape should be correct.

4. The whole code needed is in main.py in the corresponding folder. Like in main.py from line 183 to 200, that is the code to generate data, and all method you need for training is in TnpModel.

Let me know if you have more confusion!

**Comment by BenMSK** [comment]
Thank you for the fast reply! 
To sum up, for APOL dataset

1. Download the dataset and unzip 'prediction_train/test.zip'. (Is it right to use 'prediction_train/test.zip'?, not sample_trajectory.zip)
2. Use line 183 to 200 for generating -traj/track.npy file.
3. And train TnpModel using main.py

Another question;
For APOL dataset, is there any other line that I should change?
I've just changed the data directory 'APOL', and PREDALGO for 'Traphic'

Thank you, again!

**Comment by rayguan97** [comment]
Yes, I don’t think you neee to change anything else. Please let me know if you have any other questions!

**Comment by Xiejc97** [comment]
@BenMSK  
Hello! Can you run the traphic_sconv method successfully? I meet the same question that can't find traj and track.npy.

But according to what you said,
    1. Download the dataset and unzip 'prediction_train/test.zip'. (Is it right to use 'prediction_train/test.zip'?, not sample_trajectory.zip)
    2.Use line 183 to 200 for generating -traj/track.npy file.
    3.And train TnpModel using main.py

I think the three steps exsit some problems, because the step 2 is used to generating -traj/track.npy file for ARGO dataset, not APOL dataset.

If you generate the -traj/track.npy file, hope you can tell me the detailed steps, thank you vey much!
