### ISSUE TITLE
Any tool for visualizing the result trajectory on the front image?

### ISSUE THREAD

**Issue by BenMSK** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#24]
Hello!
Thank you for sharing this amazing job. It is really helpful for me studying in this field.

I have a question for the paper; (I am not so sure that I post about this in this repository;Issues)
'TraPHic: Trajectory Prediction in Dense and Heterogeneous Traffic Using Weighted Interactions'

I have successfully trained TnpModel (which is traphic_conv model, using Apolloscape dataset), and looked for visualizing the result of predicted trajectory onto sample_image as a front-view image (in sample_image.zip of ApolloScape) like 'Figure 1' in the paper.

Is there any script (or codes) in this repository for supporting that?
I think it might be obtaining homography of the image and convert coordinates of the result to the image, but I don't know where I start.

Above all, as I know, Apolloscape dataset has object's pose on world coordinate only, and it does not have the ego vehicle's pose, which means it does not have the relative pose of the objects based on the ego vehicle.

Thank you,

**Comment by rohanchandra30** [comment]
Unfortunately we don't have that capability. We don't have the required transformation to go from global coordinates (meters) to pixels.

**Comment by BenMSK** [comment]
Ok, I got it!
Then, if you don't mind, may I ask you about a process for visualizing the predicted trajectory of the result, like 'Figure 1' in the paper?
I am having a difficult time to visualize the result..
I think that, in the figure, it looks like using other datasets, not Apollo.

**Comment by rohanchandra30** [comment]
Sorry for the delayed response. Figure 1 is just meant for interpretation. It is not generated by our method. Currently, we do not provide support to visualize the trajectories. We are working on that however, and will add that functionality in future projects.

Closing this out now, please re-open if you have further questions.
