### ISSUE TITLE
[Question] What's the runtime of this algorithm?

### ISSUE THREAD

**Issue by Xiangzhaohong** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#25]
I read your paper ,but there is not mention the runtime?
I don't konw if it is possible for you to tell me the runtime of this algorithm on what kind of GPUs.
Thanks a lot!
Hope you guys are safe and healthy!

**Comment by rohanchandra30** [comment]
This is off-hand (and I can take a look in detail later), but on a single Titan Xp GPU, it takes a few (2-4) seconds to run 10-15 epochs in evaluation mode.

**Comment by Xiangzhaohong** [comment]
@rohanchandra30 Thanks for reply.
