### ISSUE TITLE
The results of the "GRIP" model

### ISSUE THREAD

**Issue by CuttlefishXuan** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#26]
Hi, thank you for making the code and pre-trained model available. I have some questions about the GRIP model.

1. I saw that you have accepted some suggestions about the code of the GRIP model, and I want to know if the pre-trained model is updated. And what are the test results obtained with the GRIP model? Cause the results I get (APOL:1.84/1.10, ARGO:27.86/24.86, LYFT:33/32) are unreasonable and not consistent with those in the paper. Did I miss something?

2. When I evaluate the GRIP model on NGSIM dataset, I get the error that the tensor size didn't match:
```
start evaluating...
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    eval(1, tr_seq_2, pred_seq_2, DATA, SUFIX)
  File "/***/Code/TrajectoryPrediction/Spectral-Trajectory-and-Behavior-Prediction/comparison_method/GRIP/def_train_eval.py", line 101, in eval
    encoder_stream.load_state_dict(torch.load(encoderloc, map_location='cuda:0'))   # encoder_stream.load_state_dict(torch.load(encoderloc))
  File "/***/anaconda3/envs/sc-glstm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Encoder:
	size mismatch for fl.weight: copying a param with shape torch.Size([95, 95]) from checkpoint, the shape in current model is torch.Size([168, 168]).
	size mismatch for fl.bias: copying a param with shape torch.Size([95]) from checkpoint, the shape in current model is torch.Size([168]).
	size mismatch for il.weight: copying a param with shape torch.Size([95, 95]) from checkpoint, the shape in current model is torch.Size([168, 168]).
	size mismatch for il.bias: copying a param with shape torch.Size([95]) from checkpoint, the shape in current model is torch.Size([168]).
	size mismatch for ol.weight: copying a param with shape torch.Size([95, 95]) from checkpoint, the shape in current model is torch.Size([168, 168]).
	size mismatch for ol.bias: copying a param with shape torch.Size([95]) from checkpoint, the shape in current model is torch.Size([168]).
	size mismatch for Cl.weight: copying a param with shape torch.Size([95, 95]) from checkpoint, the shape in current model is torch.Size([168, 168]).
	size mismatch for Cl.bias: copying a param with shape torch.Size([95]) from checkpoint, the shape in current model is torch.Size([168]).
```
Here are my paprameters in main.py:
```
TRAIN = False
EVAL = True 
epochs = 3
save_per_epoch = 5
train_seq_len = 30
pred_seq_len = 50
```
Is there anything wrong with my operation?
Thanks!

**Comment by rohanchandra30** [comment]
Thanks, we'll look into this. While the code certainly has been updated since the paper and we don't guarantee the exact same results as in the paper, the numbers you are reporting don't make sense and we've not seen those kind of numbers before.

**Comment by rohanchandra30** [comment]
Hi, just to give an update, the final results are published in this paper: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9126166

We do not report GRIP results for Argoverse and LYFT. The results for Apolloscpae and NGSIM are taken from the Apolloscape website and the GRIP original paper, respectively.

Since GRIP has released their official implementations online (https://github.com/xincoder/GRIP), we are no longer maintaining this implementation of GRIP.
