### ISSUE TITLE
About format_apollospace

### ISSUE THREAD

**Issue by zhangyanide** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#27]
In function apolloscape_to_formatted(dir, DATA_DIR, DATA_DIR_TEST, data_type):
file = DATA_DIR +  train_val_file_names[3]
generated_data = generate_data(file, data_type)
I think it just process data only one txt, not all txt. Is it enough to train the model？

Another question is in generate_data(file, data_type) function:
if data_type == 'train' or data_type == 'val':
formatted_data = np.delete(data,[4,5,6,7,8],axis=1)
when we process data in asdt_sample_ trajectory:
retain the 0th, 1th, 2tn, 3th, which is corresponding to time, agent id, length and width.
maybe it could be change to formatted_data = np.delete(data,[2,3,4,7,8],axis=1)
maybe it is my misunderstanding. Can i receive your reply, thank you

**Comment by srujanpanuganti** [comment]
Hi.

Answering your first question, you are correct, apolloscape_to_formatted() processes only one txt at a time. We had to consider that one dataset, as our behavior prediction pipeline needs adjacency matrices which indeed requires to generate a matrix of size NxN, where N is the number of agents in a dataset. The txt we considered has N = 906, which is the smallest compared to other txt files. Hence, we had to stick only to that dataset. It is enough to train the model.

Answering your second question, If you investigate the data while preparing it, you'll realize we need to do, formatted_data = np.delete(data,[4,5,6,7,8],axis=1).

I hope this answers your questions. Let me know if you have more questions.

**Comment by zhangyanide** [comment]
I notice that the output of the LSTM are mean and covariance. Can i reverse it to the real trajectories, and how to do it ?

**Comment by zhangyanide** [comment]
In data_stream.py : data_for_stream1 function
d = dict([(y,x+1) for x,y in enumerate(sorted(set(obj_IDs)))])
The obj_IDs are converted to 1 to maximum
when you change the one_dataset as :
one_dataset[np.where(one_dataset[:,1]==each_obj_ID)]  = one_obj_traj
for example: d = {0:1, 1:2, 5:3}, when you change the obj_ID from 0 to 1, the next time, you find obj_ID 1 by one_obj_traj = one_dataset[np.where(one_dataset[:,1]==each_obj_ID)], which not only contain obj_ID 1, but also contain new obj_ID 1 which original ID is 0.
So, the data for stream 1 is not correct, I want to know whether the model is correct? thankyou

**Comment by zhangyanide** [comment]
In data_stream.py for data_for_stream1 function:
d = dict([(y,x+1) for x,y in enumerate(sorted(set(obj_IDs)))])


> Hi.
> 
> Answering your first question, you are correct, apolloscape_to_formatted() processes only one txt at a time. We had to consider that one dataset, as our behavior prediction pipeline needs adjacency matrices which indeed requires to generate a matrix of size NxN, where N is the number of agents in a dataset. The txt we considered has N = 906, which is the smallest compared to other txt files. Hence, we had to stick only to that dataset. It is enough to train the model.
> 
> Answering your second question, If you investigate the data while preparing it, you'll realize we need to do, formatted_data = np.delete(data,[4,5,6,7,8],axis=1).
> 
> I hope this answers your questions. Let me know if you have more questions.
> 
> PS: Do check the Data Processing label and documentation label for more doubts relating to data preparation

The sample_trajectory_4.txt as follow:
![image](https://user-images.githubusercontent.com/38414155/81665428-451e8780-9473-11ea-8b39-cfb086618a2a.png)
it means the 2th and 3th is x_position and y position, it doesn't look like trajectory point

**Comment by srujanpanuganti** [comment]
Have you tried using the code we implemented and looked into the generated data? Because, I personally checked if everything is correct while generating the data. The data is proper. Once check and let me know.
