### ISSUE TITLE
About grip_model_APOLnotrain.pt

### ISSUE THREAD

**Issue by CuttlefishXuan** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#28]
Hi, I'm still confused about the results of the GRIP model. I have trained on the ARGO dataset, but the rmse is still ridiculously high (about 15/16). I don't know if there is something wrong with my code. I will appreciate it if you can solve my doults below.

About the pre-trained GRIP model, such as "grip_model_APOLnotrain.pt", what does the 'notrain' means? Could you please tell me the parameter settings for this model training? (epoch, batch_size, etc)

And what are the results you can get from the currrent grip models? I know that there will not be the same exact results, I just want to know the approximate number or a range.

Thank you!

**Comment by rohanchandra30** [comment]
I will look into this and get back to you in a few days.

In the meantime, the official GRIP implementation can be found here: https://github.com/xincoder/GRIP

**Comment by rohanchandra30** [comment]
Resolved in https://github.com/rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction/issues/26
