### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by Katreenlooper** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#29]
Hey,
I test the code using ours and EncDec. But where can i see the results ? 
I mean there are no images or plotting functions to compare the predicted trajectory and the real one inside the main.py functions (or exported to a directory).
I know there are some prepared images in figures folder and the saved models.   
Thanks

**Comment by rohanchandra30** [comment]
Currently the code only produces the RMSE values. We are going to include the visualization code as well sometime in the future.
