### ISSUE TITLE
About resources/trained_model

### ISSUE THREAD

**Issue by cjzswang5** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#31]
Hi,

I evaluated your trained models but results are not good as your paper. Here are my questions and issues:

1. In your `main.py`, you set `DATA = 'OTH'`, but I didn't find it in your `resources/trained_models`. What does `OTH` mean?

2. There are many `*.tar` files in `resources/trained_models`, but I can't untar them with `$ tar xvf *.tar`. And these files type are not correct
```
$ file Social_Conv_APOL_model_20-30l_26e.tar
Social_Conv_APOL_model_20-30l_26e.tar: data
```
Do these files have compression error? Are these files important?

3. Your code
https://github.com/rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction/blob/3df30c7dc787ce47ecad7e41c869daa514451a3b/ours/main.py#L51-L55
will not work when `DATA` set to other values  (except `OTH`),  so I repleased them with
```python
        if s2:
            f2 = open(DIR + 'stream2_obs_data_train.pkl', 'rb')
            g2 = open(DIR + 'stream2_pred_data_train.pkl', 'rb')
            f3 = open(DIR + 'stream2_obs_eigs_train.pkl', 'rb')
            g3 = open(DIR + 'stream2_pred_eigs_train.pkl', 'rb')
```

4. I evalutaed your trained models, two of them  (`ARGO1st` and`LYFT1st`) can not be loaded correctly. When I load these two, I got
```
$ python main.py
start evaluating ARGO1st...
computing accuracy...
0/10 in computing accuracy...
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    eval(10, tr_seq_1, pred_seq_1, DATA, SUFIX)
  File "/root/Spectral-Trajectory-and-Behavior-Prediction/ours/def_train_eval.py", line 223, in eval
    compute_accuracy_stream1(tr_seq_1, pred_seq_1, encoder_stream1, decoder_stream1, epochs)
  File "/root/Spectral-Trajectory-and-Behavior-Prediction/ours/def_train_eval.py", line 454, in compute_accuracy_stream1
    pred = generate(train, encoder, decoder)
  File "/root/Spectral-Trajectory-and-Behavior-Prediction/ours/def_train_eval.py", line 298, in generate
    out.append(sample(mu1_current , mu2_current , sigma1_current , sigma2_current , rho_current))
  File "/root/Spectral-Trajectory-and-Behavior-Prediction/ours/def_train_eval.py", line 387, in sample
    sample.append(np.random.multivariate_normal(mu, cov))
  File "mtrand.pyx", line 4084, in numpy.random.mtrand.RandomState.multivariate_normal
  File "/opt/conda/envs/glstm/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/opt/conda/envs/glstm/lib/python3.7/site-packages/scipy/_lib/_util.py", line 246, in _asarray_validated
    a = toarray(a)
  File "/opt/conda/envs/glstm/lib/python3.7/site-packages/numpy/lib/function_base.py", line 499, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```
Results of other models
```
-----------------------------------------
		ADE		FDE
-----------------------------------------
APOL1st 	3.5730		3.6391
APOL1stS1new	1.5018		1.4887
APOLsingles1	3.1047		3.2615
-----------------------------------------
ARGO1st20e	3.0335		3.0545
ARGO1stS1new	1.5716		1.5522
ARGOsingles1	4.0672		4.1507
-----------------------------------------
LYFT1stS1new	1.8584		2.2509
LYFTsingles1	7.2792		7.7997
-----------------------------------------
NGSIM1st	1.5340		1.8878
NGSIM1stS1new	1.5657		2.0239
NGSIM1stS2	1.6311		2.0420
-----------------------------------------
```
I just set `TRAIN='false'` and midified `DATA`, `SUFIX` and `s2` for different models. Did I miss something?

Thanks for your code. I am not a native english speaker, please forgive me for my bad English.

**Comment by etarakci-hvl** [comment]
Hello there, 
Is there any update regarding this question? 

Also, I wonder would you elaborate the inner dynamics of the Eval function? 

Even though s2 is activated, EVAL checks only for stream1 w/o the effect of s2.
 
This brings us to the compute_accuracy_stream1 function. Would you share your ideas on how could one compute the s2 accuracy and s1+s2 accuracy with a proper technique?

**Comment by rohanchandra30** [comment]
Apologies, I had a busy past few weeks. I will now work on this issue and respond within this week. Sorry for the inconvenience !

**Comment by cjzswang5** [comment]
update for my question 3:
I read main.py and noticed that it will not run if `TRAIN` set to `false`. Your code is no problem. Sorry for my stupid question.

**Comment by rohanchandra30** [comment]
1. 'OTH' was just a place holder codename for the NGSIM dataset results. We do not have saved models for this, unfortunately.

2. @rayguan97 what is the best way to extract these files? Is there an issue with the above-mentioned tar command?

4. That's strange. Argo1st and Lyft1st give the following results for me: 2.07/2.08 (ARGO) and 2.23/2.39 (LYFT). Can you check again and see if the problem is resolved. Sometimes, these nan/inf errors arise randomly?

**Comment by rayguan97** [comment]
(2) As to the *.tar files you are referring to, those are directly saved as tar files. To load the model, just refer to the file /comparison_method/traphic_sconv/model/model.py on line 82, using "self.net.load_state_dict(torch.load(d))", where d is the location of the tar file.

**Comment by cjzswang5** [comment]
(4) I have no idea why. It is not arise randomly. At first I thought it was because I installed a wrong version pytorch (0.4.1). but when I try your env.yml (pytorch=1.2.0), I got the same error message. Strangely, when I try pytorch=1.3.1, I got
```
$ python main.py
start evaluating ARGO1st...
computing accuracy...
0/10 in computing accuracy...
/home/huzhuoliang/workspace/Spectral-Trajectory-and-Behavior-Prediction/ours/def_train_eval.py:380: RuntimeWarning: covariance is not positive-semidefinite.
  sample.append(np.random.multivariate_normal(mu, cov))
2/10 in computing accuracy...
4/10 in computing accuracy...
6/10 in computing accuracy...
8/10 in computing accuracy...
RMSE: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan]
ADE: nan FDE: nan
```
Maybe I'm a special case. It is not an import problem for me now. I need further understanding your paper and code.  Thank you very much for your reply.
