### ISSUE TITLE
About models.py

### ISSUE THREAD

**Issue by cjzswang5** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#34]
Hi,

Thanks for your work. I read `models.py` and have a question about your model. In your code
https://github.com/rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction/blob/bf8b40bb3f50d61f57fc4114de24f339eb4df51d/ours/models.py#L110-L122

You set `graph = False` before `if graph is True:` in both `Encoder` and `Decoder`, does that mean the `if` statement will never run?

**Comment by rohanchandra30** [comment]
Yes, presently the code is not configured for GCNs. That's why it is set to off. In the future, we may visit this again and configure it for GCNs. 

In the meantime, if you are able to come up with a way to configure GCNs, we can include it as an addition.

**Comment by cjzswang5** [comment]
> Yes, presently the code is not configured for GCNs. That's why it is set to off. In the future, we may visit this again and configure it for GCNs.
> 
> In the meantime, if you are able to come up with a way to configure GCNs, we can include it as an addition.

Thanks.
