### ISSUE TITLE
The results of S1+S2 on the Apolloscape datasets

### ISSUE THREAD

**Issue by DylanCheung** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#35]
Hello! Thank you for your wonderful paper. It is insightful and interesting to read. Also thank you for sharing this repository.
I have a question regarding the results of S1+S2 on the Apolloscape datasets. 

To my knowledge, the prediction results of S1+S2 are supposed to submit to the Baidu ApolloSape leaderboard (http://apolloscape.auto/leader_board.html -> Trajectory) to validate the model performance. 
![Trajectory](https://user-images.githubusercontent.com/23057231/92345615-9e828480-f0fc-11ea-8621-e8e9f28efbcd.png)

However, I did not see any submission that has WSADE=1.12 on the Baidu ApolloSape leaderboard. **How did you get the results of S1+S2 on the Apolloscape datasets in Table I of your paper?**
![paper](https://user-images.githubusercontent.com/23057231/92345680-e30e2000-f0fc-11ea-9073-52e952766dae.png)

Thank you for your paper. I am looking forward to hearing from you.

**Comment by rohanchandra30** [comment]
Hi, thank you !

So we did not submit our method on the ApolloScape leaderboard. The results in the Table for the Apolloscape dataset were obtained by running our method directly on the dataset.

**Comment by guoyage** [comment]
Hello! I have the same question, because the prediction_result.txt file provided on the ApolloSape official website is inconsistent in time, so how do you get the real value?Thank you for your paper. I am looking forward to hearing from you.
