### ISSUE TITLE
Regarding transformation function to map prediction results to original coordinates

### ISSUE THREAD

**Issue by abojja9** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#37]
Hi,

Thanks for your work!

I got stuck with the visualising results. I'm using the following transformation to map the predictions results to the coordinate system.

```python
    # Label
    x_ = np.array(label[:, 0], copy=True)
    y_ = np.array(label[:, 1], copy=True)
    # Prediction
    pred_x = np.array(pred[:, 0], copy=True)
    pred_y = np.array(pred[:, 1], copy=True)
    x_pred = np.mean(x_) + (pred_x - np.mean(pred_x)) * (np.std(x_)/np.std(pred_x))
    y_pred = np.mean(y_) + (pred_y - np.mean(pred_y)) * (np.std(y_)/np.std(pred_y))
```
I'm trying to visualise the prediction results, but they don't make any sense although MSE seems good. So, my transformation function seems wrong.
![viz](https://user-images.githubusercontent.com/31553857/93232284-b931aa80-f747-11ea-897c-7fee8ebfd175.png)

@rohanchandra30 could you please help with it?

Thanks!

_Originally posted by @abojja9 in https://github.com/rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction/issues/32#issuecomment-692801713_

**Comment by chenxyyy** [comment]
I have the same problem as you. @abojja9 

@rohanchandra30  could you please help with it?

Thanks!
