### ISSUE TITLE
Missing TrainSet file error during data preparation

### ISSUE THREAD

**Issue by sgoel09** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#38]
Hello,

I am trying to run the models, but I am unable to prepare the formatted data. I have downloaded the resources during the installation, and have formatted the Apolloscape data as well. But while running the data_processing/data_stream.py, I am getting the following error:

![image](https://user-images.githubusercontent.com/19917408/94999887-67738780-0571-11eb-806c-29197b7f89c5.png)
I am unsure what is causing this, as it looks the program was expecting these training files to exist. Any help would be appreciated.

Thank you!

**Comment by Alamnoor** [comment]
import numpy as np
import pandas as pd
from numpy import save
csv=pd.read_csv('Apolloscape.csv')
save('TrainSet0.npy', csv)
## save the file TrainSet0.npy to desired location. May be it will solve your problem. Thanks

**Comment by rohanchandra30** [comment]
did this error come for all datasets?
