### ISSUE TITLE
data_steam.py error for eigs.packle file

### ISSUE THREAD

**Issue by Alamnoor** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#39]
#Please comment about this error if possible. Thanks 
Traceback (most recent call last):
  File "data_processing/data_stream.py", line 365, in <module>
    eigs_train = compute_eigs(tr_seq_2, 'train')
  File "data_processing/data_stream.py", line 278, in compute_eigs
    N = int(train_stream2[0][list ( train_stream2[ 0 ].keys())[ -1]].shape[ 1 ])
IndexError: list index out of range

**Comment by sanmin0312** [comment]
I have the same problem. Is there any solution to this problem?
