### ISSUE TITLE
How to  format the downloaded Argoverse trajectory data into our desired representation?

### ISSUE THREAD

**Issue by buaafish** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#4]
Use functions in data_processing/generate_data.py to format the downloaded Argoverse trajectory data into our desired representation

The instructions here are not very clear. We don't kown using which functions. Can you provide something like data_processing/format_Argoverse.py?

**Comment by rayguan97** [comment]
The code in data_processing/generate_data.py has been cleaned up. You can directly run that file, although data processing scripts are not needed to run our model. Stream 1 & 2 data are provided in resources folder. Let me know if it is still not working, or you have any question.

**Comment by rohanchandra30** [comment]
I'm closing out this issue. Feel free to re-open in case of further questions.

**Comment by haosun1992** [comment]
Hi, I am new to this area and try to run your code. But I notice that in line 168 of data_processing/generate_data.py, the code seems to be not finished. Can you provide a clear instruction or clean up the code? Thank you.

**Comment by rayguan97** [comment]
The line of code you mention seems to be redundant. Thanks for pointing this out. Other than that, I believe this code will run correctly. Just let me know if you have more questions.

**Comment by haosun1992** [comment]
Thank you for your reply. But in line 171 of data_processing/generate_data.py, 'files' is still used. Maybe  the code needs to be modified a little bit for further use.

**Comment by rayguan97** [comment]
Thanks for pointing that out! As you can see from the comment, that section is to generate multiple batches of data in case the raw data file is too large. But before that, "single" function will basically do similar thing and just put all data in one file. You can comment out that section and gave it a try. 

Just let me know if you have more questions! :)

**Comment by sraone-96** [comment]
Hi,
    I followed the instructions and was able to run "format_apolloscape.py". It creates corresponding .txt files. But, generate_data.py expects .npy files. In the README, data_stream.py was asked to use in case we want to generate the final .pkl files used by model from the .txt files created as above.
data_stream.py seems to be incomplete. Could you please look into this.
Thanks!

**Comment by rayguan97** [comment]
You will only need txt file for our method. After getting the txt file, you can run data_for_stream1 and data_for_stream2 in data_stream.py to get the desired form.

**Comment by srujanpanuganti** [comment]
Hi @sraone-96, 

You don't need to use generate_data.py to run our method. data_stream.py works perfectly with the .txt files. It has come to our notice from #12  that, the input .txt files that needs to be given to data_stream.py needs little enhancements. These enhancements will be done ASAP and will be notified. Please check back soon.

Regards,
Srujan

**Comment by srujanpanuganti** [comment]
@sraone-96 , The above issue is now resolved

**Comment by TsuTikgiau** [comment]
Hello! I tried to process the raw argoverse data via data_processing/generate_data.py, but I cannot find the model.import_data package used [here](https://github.com/rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction/blob/8a22e7e2e5d0834925f761ff58642454caa18e6c/data_processing/generate_data.py#L7). Do I miss something? Thank you!
