### ISSUE TITLE
Missing trainSet0.py error during data stream

### ISSUE THREAD

**Issue by LiDinga** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#42]
Hello,
I have run the generate_data.py to generate the trainSet0.txt, trainSet0-track.npy and trainSet0-traj.npy by using the Argoverse dataset. In the data_stream.py, the trainSet0.npy should be provided, which is considered as the input of the function data_for_stream1. However, I can not get the trainSet0.npy in the generate_data.py or other related files.  How to generate the trainSet0.npy? Thanks~
![image](https://user-images.githubusercontent.com/48577880/99259764-724e5700-2855-11eb-8bd4-f5e6f419b177.png)

**Comment by rohanchandra30** [comment]
Are you still having this error? 

This is surprising since no one else had this issue.

**Comment by sanmin0312** [comment]
I have the same issue.
by running "generate_data.py", I can generate trainSet0.txt, trainSet0-track.npy and trainSet0-traj.npy of Argoverse dataset but there is no trainSet0.npy.
