### ISSUE TITLE
Bug in formatting apolloscape dataset

### ISSUE THREAD

**Issue by zqzqz** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#48]
In the file `format_apolloscape.py`, line 117

```python
    if data_type == 'train' or data_type == 'val':
        formatted_data = np.delete(data,[4,5,6,7,8],axis=1)
    elif data_type == 'test':
        formatted_data = np.delete(data,[2,5,6,7,8,9],axis=1)
```

In the mode of train and val, why remove index 4 (y position)? Index 9 is heading, why not remove it? 
The formatting in test mode seems reasonable to me.

Also, the data of traces for training/testing looks wrong. `resources/data/APOL/stream1_obs_data_train.pkl` for instance:

```
[1.725, 0.878],
[2.139, 1.493],
[2.422, 1.14 ],
[2.164, 1.403],
[2.495, 1.487]
```

This seems to be obstacle length and width, not x and y position.

Is this a real bug? If so, the mistake is very severe. I am not sure whether the pre-trained models are affected as well.

Thanks!

**Comment by Xiejc97** [comment]
In the file format_apolloscape.py, line 192, the DATA_DIR = dir + 'sample_trajectory/asdt_sample_ trajectory/', so it processes the data in the sample_trajectory folder downloaded from the official website, not the data in the prediction_train folder.

 In the  sample_trajectory folder, the meaning of the data in each row is: timestamp, id, width, length, type, position_x, position_y, velocity_x, velocity_y(you can reference the website https://github.com/ApolloScapeAuto/dataset-api/tree/master/trajectory_prediction). 
But in the  prediction_train folder, the meaning of the data in each row is: frame_id, object_id, object_type, position_x, position_y, position_z, object_length, object_width, object_height, heading.

So the code remove index 4,5,6,7,8, It actually removes type, position_x, position_y, velocity_x, velocity_y.

Do you run the code successfully? We can communicate with each other.

**Comment by zqzqz** [comment]
Thanks for your information. Now I understand why the code removes indexes 45678. It is misleading though since the users will not use sample trajectories as training and validation data... Anyway, by reading data_stream.py, I think the columns should be maintained include frame_id, object_id, position_x, position_y and an extra dataset id.

I actually directly used the downloaded data like `resources/data/APOL/stream1_obs_data_train.pkl` to reproduce the work. Then I have the second question: the data in those files looks weird to me. I think the stream1 data is the trajectories (i.e., sequences of x/y positions). But from my observation, the values in stream1_obs_data_train.pkl, for instance, are all less than 3, which are inconsistent with the original Apolloscape dataset, and do not looks like trajectories. Could you please confirm this?

The problem only exists in Apolloscape dataset.

**Comment by Xiejc97** [comment]
@zqzqz 
I also have a lot of doubts about the code. At present I want to test the apollo data set with the Social_Conv method，but I meet some problems, I hope you can help me explain these questions.

Q1: When I run python setup.py, I can't download the resourses folder, can you share the resources folder with me？
Q2: In comparision_method/traphic_sconv, I want to use the apollo dataset with social conv. When preprocessing the apollo data set, in addition to running the format_apolloscape.py file, do you need to run data_stream.py?
Q3: When preprocessing the apollo dataset, why not process the prediction_train file, but process the sample_trajectory？ 

Thank you very much!

**Comment by zqzqz** [comment]
@Xiejc97 
Q1: The script is calling google services. Can you access Google? :) 
Q2: Yes you need both. data_stream.py is going to use the output of format_apolloscape.py
Q3: You should process prediction_train for both training and validation. Obviously, the developer does not clean the code in format_apolloscape.py. You should replace the path by yourself.

Just my understanding.

**Comment by Xiejc97** [comment]
@zqzqz 
For Q1, every time I run setup.py, it always shows that there is a connection problem. If this file runs successfully, will it download the resources folder? If it is convenient for you, can you share the contents of this resources folder with me?

For Q3, I agree with you that the file in prediction_train.zip should also be used for traini and val, but the developer used sample_trajectory.zip in the format_apolloscape.py file. I would like to ask, if you use the files in prediction_train.zip, which sub-files should be selected for training and which sub-files for val? Because there are many files in the prediction_train folder, such as result_9048_1_frame.txt, result_9048_3_frame.txt and so on. Besides, in addition to modifying the path of line 192 in the format_apolloscape.py file, do some of the above functions also need to be modified?

Because I just started to study this trajectory prediction, the question that I asked you is easy, I hope you can understand, thank you very much!

**Comment by zqzqz** [comment]
@Xiejc97 Your questions are about basic programming and machine learning, not specific to trajectory prediction nor this repo. I suggest you solve the problems offline, e.g., through emails.

**Comment by zqzqz** [comment]
> @zqzqz
> For Q1, every time I run setup.py, it always shows that there is a connection problem. If this file runs successfully, will it download the resources folder? If it is convenient for you, can you share the contents of this resources folder with me?
> 
> For Q3, I agree with you that the file in prediction_train.zip should also be used for traini and val, but the developer used sample_trajectory.zip in the format_apolloscape.py file. I would like to ask, if you use the files in prediction_train.zip, which sub-files should be selected for training and which sub-files for val? Because there are many files in the prediction_train folder, such as result_9048_1_frame.txt, result_9048_3_frame.txt and so on. Besides, in addition to modifying the path of line 192 in the format_apolloscape.py file, do some of the above functions also need to be modified?
> 
> Because I just started to study this trajectory prediction, the question that I asked you is easy, I hope you can understand, thank you very much!

@Xiejc97 
1. Try fixing your network first, e.g., usue VPNs.
2. The code is not clean. You need to fix it if necessary. Sorry I cannot help you with all the details.

**Comment by Xiejc97** [comment]
@zqzqz 
Hello!
For APOL, Lyft and NGSIM, when I run traphic_sconv/main.py, I did not find any code that uses the stream1_obs_data_train.pkl and other files generated from data_stream.py. And it will report an error: no such file resources/data/xxx(such as APOL)/train/trainSet0-traj.npy.

I checked the code carefully, and find in model/Prediction/utils.py, the ngsimDataset class load the trainSet0-traj.npy and trainSet0-track.npy in line 73 and 75.  I find in the traphic_sconv/model/import data.py, the merge function will save the trainSet0-traj.npy and trainSet0-track.npy. But in the main.py and data_processing, none of them call the merge function to generate npy files for traj and track.

So I want to ask for each kind of dataset, how to generate the trainSet0-traj.npy and trainSet0-track.npy in ../resources/data/APOL/train?

Hope you can help me explain this problem, thank you very much!
