### ISSUE TITLE
Bug in MSE calculation of GRIP

### ISSUE THREAD

**Issue by zqzqz** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#49]
In `comparison_method/GRIP/def_train_val.py`.

```python
def MSE(y_pred, y_gt, device=device):
    # y_pred = y_pred.numpy()
    y_pred = y_pred.cpu().detach().numpy()
    y_gt = y_gt.cpu().detach().numpy()
    acc = np.zeros(np.shape(y_pred)[:-1])
    muX = y_pred[:,:,0]
    muY = y_pred[:,:,1]
    x = np.array(y_gt[:,:, 0])
    x = x
    y = np.array(y_gt[:,:, 1])
    y = y
    # print(muX,x,muY,y)
    acc = np.power(x-muX, 2) + np.power(y-muY, 2)
    lossVal = np.sum(acc, axis=0)/len(acc)
    # lossVal = np.sum(acc, axis=0)
    return lossVal
```

No. `y_pred` and `y_gt` here are in shape of (batch_size, channel count (2 for x and y), max object/node count, sequence length/time steps). `MSE` function here is assuming the shape is (batch_size, sequence length, channel count). As a result, the calculated MSE by this function seems to be wrong.

Thanks!

**Comment by Xiejc97** [comment]
@zqzqz 
Hello! In addition to the problem you mentioned above, do you check the `scale_train` function in `comparison_method/EncDec/def_train_eval.py`,

`def scale_train(train_tensor, target_tensor):

    train_tensor_x = train_tensor[:,0,:].clone()
    train_tensor_y= train_tensor[:,1,:].clone()
    target_tensor_x= target_tensor[:,0,:].clone()
    target_tensor_y= target_tensor[:,1,:].clone()

    train_tensor[:,0,:] = torch.mean(target_tensor_x) + (train_tensor_x - torch.mean(train_tensor_x))*( (torch.std(target_tensor_x)/ torch.std(train_tensor_x)))
    train_tensor[:,1,:] = torch.mean(target_tensor_y) + (train_tensor_y- torch.mean(train_tensor_y))*( (torch.std(target_tensor_y)/ torch.std(train_tensor_y)))

    return train_tensor


The `train_tensor` and `target_tensor` 's shape is (batch_size, sequence length, channel count), but in the function `train_tensor_x = train_tensor[:,0,:].clone()`, in order to get x, shouldn't the third dimension channel count be indexed?

**Comment by rohanchandra30** [comment]
Hi @Xiejc97  Sorry, the main developers of this code have left the project and I am unable to immediately take a look into this. I will take a look as soon as I get time.

But this is a new concern and I haven't seen other people having this concern, so that's strange. I will take a look.
